name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t nodejs-ci-cd .
          docker tag nodejs-ci-cd:latest nodejs-ci-cd:$GITHUB_SHA