name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Build and push Docker image
        run: |
          docker build -t nodejs-ci-cd .
          docker tag nodejs-ci-cd:latest ${{ secrets.DOCKER_REPO_URL }}/nodejs-ci-cd:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_REPO_URL }}/nodejs-ci-cd:latest